name: punto
version: '3'
services:
  punto-db:
    container_name: punto-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  punto-db-express:
    container_name: punto-db-express
    image: mongo-express
    depends_on:
      - punto-db
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: punto-db
      ME_CONFIG_MONGODB_HOSTNAME: punto-db

  punto-api:
    container_name: punto-api
    build: ./api
    ports:
      - "3000:3000"
    links:
      - punto-db
    depends_on:
      - punto-db

  punto-app:
    container_name: punto-app
    build: ./app
    ports:
      - "80:80"
    links:
      - punto-db
    depends_on:
      - punto-api

volumes:
  db_data: