name: punto
version: '3'
services:
  api:
    container_name: punto-api
    build: ./api
    ports:
      - "3000:3000"
    links:
      - db
  db:
    container_name: punto-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  app:
    container_name: punto-app
    build: ./app
    ports:
      - "80:80"
    links:
      - db

volumes:
  db_data: