FROM node
#FROM node:lts-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files
COPY . /app

# Build the application
RUN npm run build

# Expose the port on which the application will run
EXPOSE 80

# Start the application
CMD ["npm", "start"]
