FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app source code
COPY . /usr/src/app

# Expose port
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]
